version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: fitnesstracker_db
    restart: always
    environment:
      POSTGRES_DB: FitnessTracker
      POSTGRES_USER: your_name
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
